stages:
  - build
  - deploy

variables:
  TAIS_LATEST_IMAGE: $CI_REGISTRY_IMAGE/tais:latest
  WEB_LATEST_IMAGE: $CI_REGISTRY_IMAGE/web:latest

  TAIS_STABLE_IMAGE: $CI_REGISTRY_IMAGE/tais:stable
  WEB_STABLE_IMAGE: $CI_REGISTRY_IMAGE/web:stable

build stable:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -f docker/tais/Dockerfile -t $TAIS_STABLE_IMAGE .
    - docker push $TAIS_STABLE_IMAGE
    - docker build -f docker/web/Dockerfile -t $WEB_STABLE_IMAGE .
    - docker push $WEB_STABLE_IMAGE
  only:
    - tags
  environment: production
  tags:
    - docker

deploy_to_production:
  image: cdrx/rancher-gitlab-deploy
  stage: deploy
  services:
    - docker:dind
  script:
    - upgrade --environment Production --stack TAIS --service tais --new-image $TAIS_STABLE_IMAGE --no-finish-upgrade --debug
    - upgrade --environment Production --stack TAIS --service web --new-image $WEB_STABLE_IMAGE --no-finish-upgrade --debug
  only:
    - tags
  environment: production
  tags:
    - docker


build latest:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -f docker/tais/Dockerfile -t $TAIS_LATEST_IMAGE .
    - docker push $TAIS_LATEST_IMAGE
    - docker build -f docker/web/Dockerfile -t $WEB_LATEST_IMAGE .
    - docker push $WEB_LATEST_IMAGE
  only:
    - /master/
  environment: development
  tags:
    - docker

deploy_to_development:
  image: cdrx/rancher-gitlab-deploy
  stage: deploy
  services:
    - docker:dind
  script:
    - upgrade --environment Development --stack TAIS --service tais --new-image $TAIS_LATEST_IMAGE --debug
    - upgrade --environment Development --stack TAIS --service web --new-image $WEB_LATEST_IMAGE --debug
  only:
    - /master/
  environment: development
  tags:
    - docker
