version: '2'

services:
  rocketchat:
    image: rocket.chat:0.69.2
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - ADMIN_USERNAME=admin
      - ADMIN_PASS=admin
    depends_on:
      - mongo
    ports:
      - 3000:3000

  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --oplogSize 128

  rouana:
    build:
      context: .
      dockerfile: ./docker/tais/Dockerfile
    restart: unless-stopped
    environment:
      - TRAINING_EPOCHS=300
      - CREDENTIALS=/rouana/credentials.yml
      - ROCKETCHAT_URL=rocketchat:3000
      - MAX_TYPING_TIME=8
      - MIN_TYPING_TIME=1
      - WORDS_PER_SECOND_TYPING=10
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - TAIS_USERNAME=tais
      - TAIS_PASSWORD=tais
    volumes:
      - ./rouana:/rouana
      - ./scripts:/scripts
    depends_on:
      - rocketchat

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    restart: unless-stopped
    environment:
      - PORT=8000
      - ROCKETCHAT_URL=http://localhost:3000
      - ALLOWED_HOSTS=localhost
      - PREFIX_URL=
    volumes:
      - ./web:/web
    ports:
      - 8000:8000
    depends_on:
      - webdb

  webdb:
    image: postgres:10.5
    restart: unless-stopped
    volumes:
      - ./web/postgres-data:/var/lib/postgresql/data
